---
- hosts: all
  become: false
  gather_facts: false
  tasks:

   - assert:
       that:
         - "artemii_password is defined"
         - "artemii_username is defined"
       msg: "'artemii_password' must be defined"

   - debug: var=artemii_password
   - debug: var=artemii_username
   - shell: echo $URL
     register: echo
   - debug: var=echo
